# Form implementation generated from reading ui file 'ui/home.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(423, 386)
        MainWindow.setWindowOpacity(18.0)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inp = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inp.setGeometry(QtCore.QRect(52, 40, 251, 31))
        self.inp.setObjectName("inp")
        self.qr = QtWidgets.QLabel(parent=self.centralwidget)
        self.qr.setGeometry(QtCore.QRect(80, 100, 251, 221))
        self.qr.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.qr.setText("")
        self.qr.setObjectName("qr")
        self.but = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but.setGeometry(QtCore.QRect(310, 40, 52, 31))
        self.but.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/../res/enter.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.but.setIcon(icon)
        self.but.setIconSize(QtCore.QSize(32, 32))
        self.but.setObjectName("but")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 423, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QR Maker"))
        self.inp.setText(_translate("MainWindow", "http://"))
        self.inp.setPlaceholderText(_translate("MainWindow", "http://ornek-site.com"))
